services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: ".env"
    environment:
      - PORT
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: always
    depends_on: 
      postgres:
        condition: service_healthy
    networks:
      - backend

  postgres:
    image: postgres:16.3
    env_file: ".env"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend: 